[workspace]
members = [
    "crates/parser",
    "crates/checker",
    "crates/runtime",
    "crates/repl",
    "crates/builtins",
    "crates/prettify",
    "crates/syntax-highlighter",
    "crates/reports",
    "crates/tests",
    "vscode-syntax/rust-wasm",
]
resolver = "3"
